# Generated by Django 2.1.2 on 2018-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='path')),
                ('file', models.FileField(upload_to='store', verbose_name='файл')),
                ('name_file', models.CharField(max_length=200)),
            ],
        ),
    ]
